name: Code quality

on:
  push:
    branches:
      - master

permissions:
  checks: write
  contents: read
  deployments: write
  pull-requests: read
  statuses: read

jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: none
          tools: phpcs

      - name: Run lint
        uses: wearerequired/lint-action@v2
        with:
          php_codesniffer: true
          php_codesniffer_args: "--standard=$GITHUB_WORKSPACE/php_codesniffer.xml"
          github_token: ${{ secrets.GITHUB_TOKEN }}
